[build]
  command = "npm run build"
  publish = "__sapper__/export"

[dev]
  command = "npm run dev"


[[redirects]]
  from = "/img/tiny/*"
  to = "https://master--theaironearth.netlify.com/img/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/img/small/*"
  to = "https://master--theaironearth.netlify.com/img/:splat?nf_resize=fit&w=500"
  status = 302

[[redirects]]
  from = "/img/medium/*"
  to = "https://master--theaironearth.netlify.com/img/:splat?nf_resize=fit&w=800"
  status = 302

[[redirects]]
  from = "/img/large/*"
  to = "https://master--theaironearth.netlify.com/img/:splat?nf_resize=fit&w=1200"
  status = 302

[[redirects]]
  from = "/img/original/*"
  to = "https://master--theaironearth.netlify.com/img/:splat"
  status = 302
